---
title: "ClusteringAssignment"
author: "Nicholas Smith"
date: "2025-02-24"
output: word_document
---


```{r}
library(tidyverse)
library(tidymodels)
library(cluster)
library(factoextra)
library(dendextend)
```

```{r}
trucks = read_csv("trucks-1-ClstrAssgn.csv")
```

```{r}
ggplot(trucks, aes(x=Distance,y=Speeding)) +
  geom_point()
```

```{r}
trucks = trucks %>%
  select(-Driver_ID) %>%
  drop_na()
```

```{r}
kmeans_recipe = recipe(~ Distance + Speeding, trucks)

trucks_dummy = kmeans_recipe %>%
  step_dummy(all_nominal(), one_hot = TRUE) %>%
  step_scale(all_numeric()) %>%
  step_center(all_numeric())

trucks_dummy = prep(trucks_dummy, trucks)

trucks_cleaned = bake(trucks_dummy, trucks)
```

```{r}
summary(trucks_cleaned)
```

```{r}
set.seed(64)
clusts = 
  tibble(k = 2) %>%
  mutate(kclust = map(k, ~kmeans(trucks_cleaned,.x)),
         tidied = map(kclust, tidy),
         glanced = map(kclust, glance),
         augmented = map(kclust,augment,trucks_cleaned))
clusts
```

```{r}
clusters = 
  clusts %>%
  unnest(cols = c(tidied))

assignments = 
  clusts %>%
  unnest(cols = c(augmented))

clusterings = 
  clusts %>%
  unnest(cols = c(glanced))
```

```{r}
p1 = 
  ggplot(assignments, aes(x=Distance, y=Speeding)) + 
  geom_point(aes(color = .cluster), alpha=0.8) +
  facet_wrap(~ k)

p1
```

```{r}
ggplot(clusterings, aes(k,tot.withinss)) +
  geom_line() +
  geom_point()
```

```{r}
set.seed(412)
clusts = 
  tibble(k = 1:8) %>%
  mutate(kclust = map(k, ~kmeans(trucks_cleaned,.x)),
         tidied = map(kclust, tidy),
         glanced = map(kclust, glance),
         augmented = map(kclust,augment,trucks_cleaned))
clusts
```

```{r}
clusters = 
  clusts %>%
  unnest(cols = c(tidied))

assignments = 
  clusts %>%
  unnest(cols = c(augmented))

clusterings = 
  clusts %>%
  unnest(cols = c(glanced))
```

```{r}
p1 = 
  ggplot(assignments, aes(x=Distance, y=Speeding)) + 
  geom_point(aes(color = .cluster), alpha=0.8) +
  facet_wrap(~ k)

p1
```

```{r}
ggplot(clusterings, aes(k,tot.withinss)) +
  geom_line() +
  geom_point()
```
